allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - framer-motion@12.40.0
  - motion-dom@12.40.0
  - motion@12.40.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
