allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - framer-motion@12.40.0
  - motion-dom@12.40.0
  - motion@12.40.0
  - '@hookform/resolvers@5.4.3'
  - react-hook-form@7.83.0
  - '@types/react-dom@19.2.5'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
